---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

# Olá, seja bem vindo(a)! :deciduous_tree: :smiley: :grin: :deciduous_tree:
:calendar: **19 de Março de 2021**

:alarm_clock: **18h00min - 22h00min**

**Este repositório está licenciado nos termos da licença MIT.**

# Descrição

Este repositório guarda os arquivos .Rmd e .R usados na palestra intitulada **"Aprendizado de Máquina na Mensuração Florestal: Técnicas, Modelagem e Aplicação Web"** ministrada pelo **Prof. Dr. Deivison Venicio Souza** no evento **"Mensuração Florestal: sucessos do passado, desafios correntes e perspectivas futuras"** organizado pelo **Prof. Dr. Rodrigo Geroni** no âmbito da disciplina de **Mensuração Forestal** do Programa de Pós-Graduação em Ciências Florestais da Universidade Federal Rural da Amazônia (UFRA).

# Slide da palestra

O slide da palestra síncrona intitulada **"Aprendizado de Máquina na Mensuração Florestal: Técnicas, Modelagem e Aplicação Web"** está disponível a seguir.

# :ledger: [Slide da apresentação](https://deivisonsouza.github.io/ML-Mensuracao-Florestal/)

# Palestrante :deciduous_tree:

**Deivison Venicio Souza** possui graduação em :deciduous_tree: **Engenharia Florestal** :deciduous_tree: pela Universidade Federal Rural da Amazônia (2008), Mestrado em Ciências Florestais pela Universidade Federal Rural da Amazônia (2011) e Doutorado em Engenharia Florestal pela Universidade Federal do Paraná. No período de 2009 a 2011 exerceu o cargo de Analista Ambiental da Secretaria Estadual de Meio Ambiente do Pará, na Gerência de Projetos Agrossilvipastoris (GEPAF), com atuação direta na etapa de análise técnica, para fins de licenciamento ambiental, de Planos de Manejo Florestal Sustentável (PMFS), Projetos de Desbastes e Reflorestamento e Supressão Florestal. Desde 2011 é professor da Faculdade de Engenharia Florestal da Universidade Federal do Pará, Campus Universitário de Altamira, Pará. É responsável por ministrar as disciplinas Estatística Básica, Dendrometria, Experimentação Florestal e Inventário Florestal, integrantes do desenho curricular do Curso de Graduação em Engenharia Florestal. Tem experiência na área de Gestão e Manejo dos Recursos Florestais, com ênfase em Silvicultura de Florestas Naturais, Inventário Florestal e Mensuração Florestal. Atualmente, seus interesses científicos incluem o uso da inteligência artificial na conservação da biodiversidade (com ênfase no uso de visão computacional) e emprego de técnicas de aprendizado de máquina na modelagem preditiva de variáveis biométricas, com uso das Linguagens R e Python.
